#!/usr/bin/guile -s
!#

(load "./config.scm")
(load "./user-interact.scm")
(define current-file-name (assoc-ref config-pairs 'current-file-name))
(display "current file name is: ")
(display current-file-name)
(newline)
(display "checking ask-file-name procedure...")
(newline)
(define new-file-name (ask-file-name))
(display "the return value of ask-file-name is: ")
(display new-file-name)
(newline)
(display "checking set-new-file-to-edit procedure...")
(newline)
(define receiver (set-new-file-to-edit new-file-name))
(display "the return value is: ")
(display receiver)
(newline)
(display "current file name is: ")
(display (assoc-ref config-pairs 'current-file-name))
(newline)
(display "checking display-help-message procedure...")
(newline)
(if (eq? (display-help-message) 'func-end-ok)
	(begin (display "get the right symbol returned")(newline))
	(begin (display "failed to return the right symbol")(newline))
)
