(use-modules (ice-9 textual-ports))

(define (display-entire-file file-name)
	(let ((input-port (open-input-file file-name)))
		(display "[start of file]")
		(newline)
		(let loop ()
			(let ((line (get-line input-port)))
				(if (eof-object? line)
					(begin
						(display "[end of file]")
						(newline)
						(close input-port)
					)
					(begin
						(display line)
						(newline)
						(loop)
					)
				)
			)
		)
	)
)
